name: Build Check - All LTS Kernels

permissions:
  contents: write
  actions: write

on:
  push:
  workflow_dispatch:

jobs:
  build-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          
          
          # Android 14 - Kernel 6.1 LTS
          - android_version: "android14"
            kernel_version: "6.1"
            sub_level: "X"
            os_patch_level: "lts"
          
         

    name: Build Check
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
