name: Kernel Config - A14 6.1

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:

jobs:
  build-kernels-a14-6-1:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "134"
            os_patch_level: "2025-05"
          - sub_level: "145"
            os_patch_level: "2025-08"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
