name: Build Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches:
      - mksu

jobs:
 
  build-a14-6-1:
    uses: ./.github/workflows/kernel-a14-6-1.yml
    secrets: inherit

 
